<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildProjectDirectory)/../oscommon.targets" />
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <Configurations>Debug;Release;LinuxDebug</Configurations>
    <Platforms>AnyCPU</Platforms>
    <RootNamespace>OneScript.BinaryData</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'LinuxDebug' ">
    <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
    <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OneScript.Core\OneScript.Core.csproj" />
  </ItemGroup>
</Project>
