using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using ScriptEngine.HostedScript;
// Пространство имен для стандартных коллекций
using ScriptEngine.HostedScript.Library;
// Пространство имен для ValueFactory
using ScriptEngine.Machine;
namespace DemoHelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            // Это код 1С, который будет выполнен, в случае отсутствия параметров исполняемого файла
            string scriptStr = 
                "Сообщить(\"This text generated by OneScript\");" +
                "Сообщить(\"Please, use following syntax: DemoHelloWorld.exe [script file name]\")";

            HostedScriptEngine hostedScript = new HostedScriptEngine();

            ScriptEngine.Environment.ICodeSource source;

            if (args.Length == 0)
            {
                // Получаем источник кода из строки
                source = hostedScript.Loader.FromString(scriptStr);
            }
            else
            {
                // Получаем источник кода из файла
                source = hostedScript.Loader.FromFile(args[0]);
            }

            // Создаем объект, куда OneScript будет осуществлять вывод
            MyHost myOut = new MyHost();
            // Создаем процесс выполнения
            ScriptEngine.HostedScript.Process process = hostedScript.CreateProcess(myOut, source);
            // Запускаем выполнение скрипта
            int result = process.Start();

            if (result != 0)
            {
                Console.WriteLine("Execution error: {0}", result);
            }
            else
            {
                Console.WriteLine("Execution successfully completed.");
            }
        }
    }

        // Класс выводящий вывод OneScript на экран
        public class MyHost : IHostApplication
        {
            public void Echo(string str, MessageStatusEnum status = MessageStatusEnum.Ordinary)
            {
                Console.WriteLine(str);
            }
            public void ShowExceptionInfo(Exception exc)
            {
                Console.WriteLine( "Exception: " + exc.Message);
            }
            public bool InputString(out string result, int maxLen)
            {
                result = "строка введена";
                return true;
            }
            public string[] GetCommandLineArguments()
            {
                return new string[0];
            }
        }
}
