/*----------------------------------------------------------
This Source Code Form is subject to the terms of the 
Mozilla Public License, v.2.0. If a copy of the MPL 
was not distributed with this file, You can obtain one 
at http://mozilla.org/MPL/2.0/.
----------------------------------------------------------*/
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyCompany("BeaverSoft")]
[assembly: AssemblyCopyright("Copyright (c) 2017 EvilBeaver")]
[assembly: AssemblyConfiguration("Commit 2a614c0")]
[assembly: AssemblyVersion("1.0.18.0")]
[assembly: AssemblyFileVersion("1.0.18.0")]
[assembly: AssemblyInformationalVersion("1.0.18.0")]

internal sealed class ThisAssembly
{
	internal const string AssemblyCompany = "BeaverSoft";

	internal const string AssemblyCopyright = "Copyright (c) 2017 EvilBeaver";

	internal const string AssemblyConfiguration = "Commit 2a614c0";

	internal const string AssemblyVersion = "1.0.18.0";

	internal const string AssemblyFileVersion = "1.0.18.0";

	internal const string AssemblyInformationalVersion = "1.0.18.0";

	private ThisAssembly()
	{
	}
}