/*----------------------------------------------------------
This Source Code Form is subject to the terms of the 
Mozilla Public License, v.2.0. If a copy of the MPL 
was not distributed with this file, You can obtain one 
at http://mozilla.org/MPL/2.0/.
----------------------------------------------------------*/
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("BeaverSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2016 EvilBeaver")]
[assembly: System.Reflection.AssemblyConfiguration("Commit 2a614c0")]
[assembly: System.Reflection.AssemblyVersion("1.0.15.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.15.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.15.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "BeaverSoft";

    internal const string AssemblyCopyright = "Copyright (c) 2016 EvilBeaver";
    
    internal const string AssemblyConfiguration = "Commit 2a614c0";
    
    internal const string AssemblyVersion = "1.0.14.0";
    
    internal const string AssemblyFileVersion = "1.0.14.0";
    
    internal const string AssemblyInformationalVersion = "1.0.14.0";
    
    private ThisAssembly() {
    }
}
